#! /usr/bin/python

"""
Start Jupyter lab like a standalon application.
"""

import sys
import subprocess as sp
import time
import secrets
import re
import os

# change this to whatever you want to use
browser_cmd = 'chromium --app=%s'
virtualenv = None 

# create virtualenv command
if virtualenv:
    venv_cmd = ['source', virtualenv, '&&']
else:
    venv_cmd = []

# create jupyter lab command string
token = secrets.token_hex(32)
lab_cmd = [
    'jupyter lab',
    '--NotebookApp.token=' + token,
    '--no-browser',
]
lab_cmd_str = ' '.join(venv_cmd + lab_cmd + sys.argv[1:])

# create list notebook kernel command string
nblist_cmd = ['jupyter notebook list']
nblist_cmd_str = ' '.join(venv_cmd + nblist_cmd)

# start jupyter lab server
server = sp.Popen(lab_cmd_str, shell=True)

# check if server started and aquire url
pattern = re.compile(r'http://localhost:\d+/\?token=([\w]+)')
timeout = 10
tic = time.time()
found_server = False
while not found_server:
    toc = time.time()
    if tic + timeout < toc:
        raise TimeoutError('Server not found.')

    nb_list = sp.check_output(nblist_cmd_str, shell=True).decode()
    nb_list = nb_list.split('\n')[1:-1]

    for line in nb_list:
        url = line.split(' :: ')[0]
        other_token = re.match(pattern, url).groups()[0]

        if other_token == token:
            found_server = True
            break
    else:
        time.sleep(0.1)

# start browser
cmd = browser_cmd % url
browser = sp.Popen(cmd.split())

print('Waiting for browser to be closed.')
browser.wait()
server.terminate()
print()
